package net.datenwerke.rs.oauth.service.oauth;

import com.google.inject.ImplementedBy;

@ImplementedBy(DummyOAuthenticationServiceImpl.class)
public interface OAuthAuthenticationService {

   /**
    * Generates and saves an OAuth2 refresh token into the given datasink, which is
    * necessary for allowing the app to access the OAuth2 service in future usage
    * without requiring the user to manually authenticate.
    * 
    * @param authenticationCode the authentication code generated by the OAuth2
    *                           service
    * @param oAuthDatasink      the datasink to save the refresh token to
    * @param redirectUri        the redirect uri
    */
   void generateRefreshToken(String authenticationCode, OAuthAuthenticatable oAuthDatasink, String redirectUri)
         throws Exception;

   /**
    * Generates the URL necessary for OAuth2 authentication.
    * 
    * @param oAuthDatasink the OAuth2 datasink
    * @return the authentication URL
    */
   String generateAuthenticationUrl(OAuthAuthenticatable oAuthDatasink);

   /**
    * Get redirect URI needed for OAuth2-authenticated services. This redirect URI
    * must be entered into the respective apps in the app-developer administration.
    * 
    * @return the redirect URI
    */
   String getRedirectUri();
}