package net.datenwerke.rs.core.service.reportmanager.output;

import net.datenwerke.rs.core.service.reportmanager.engine.CompiledReport;

/**
 * 
 *
 */
public interface ReportOutputGenerator {

   /**
    * 
    * @return The generator's format
    */
   public String[] getFormats();

   /**
    * Returns true if this generator should be used if the format is not
    * recognized.
    * 
    */
   public boolean isCatchAll();

   /**
    * Returns an empty {@link CompiledReport} object to specify the type of report
    * that is generated by this generator.
    * 
    */
   public CompiledReport getFormatInfo();
}
