package net.datenwerke.rs.scheduleasfile.client.scheduleasfile;

public enum StorageType {
	FTP, FTP_SCHEDULING,
	SFTP, SFTP_SCHEDULING,
	FTPS, FTPS_SCHEDULING,
	LOCALFILESYSTEM, LOCALFILESYSTEM_SCHEDULING,
	SAMBA, SAMBA_SCHEDULING,
	SCP, SCP_SCHEDULING,
	EMAIL, EMAIL_SCHEDULING
}
