package net.datenwerke.rs.scheduleasfile.client.scheduleasfile;

public enum StorageType {
   FTP, FTP_SCHEDULING, 
   SFTP, SFTP_SCHEDULING, 
   FTPS, FTPS_SCHEDULING, 
   LOCALFILESYSTEM, LOCALFILESYSTEM_SCHEDULING,
   SAMBA, SAMBA_SCHEDULING, 
   SCP, SCP_SCHEDULING, 
   DROPBOX, DROPBOX_SCHEDULING, 
   ONEDRIVE, ONEDRIVE_SCHEDULING,
   GOOGLEDRIVE, GOOGLEDRIVE_SCHEDULING, 
   BOX, BOX_SCHEDULING, 
   EMAIL, EMAIL_SCHEDULING, 
   AMAZONS3, AMAZONS3_SCHEDULING, 
   TABLE_DATASINK, TABLE_DATASINK_SCHEDULING,
   PRINTER, PRINTER_SCHEDULING
}
